    <link rel="stylesheet" href="./css/footer.css">
    <link rel="stylesheet" href="./css/reset.css">
    <link rel="stylesheet" href="./css/header.css">
    <link rel="stylesheet" href="./css/page_journal.css">
    <link rel="stylesheet" href="./css/page_d_acueil.css">
    <link rel="stylesheet" href="./css/page_des_emissions.css">
    <link rel="stylesheet" href="./css/page_lycee_membre.css">
    <link rel="stylesheet" href="./css/page_lycee_mdl.css">
    <link rel="stylesheet" href="./css/page_membre.css">
